export const PAGES_HELPER = {
    ['step-age']: {order: 1, key: 'age' },
    ['step-goal']: {order: 2, key: 'goal' },
    ['step-target-body']: {order: 3, key: 'targetBody' },
    ['step-body-type']: {order: 4, key: 'bodyType' },
    ['step-level-of-fat']: {order: 5, key: 'bodyFat' }
    // ['step-problem-areas']: {order: 5, key: 'currentProblemAreas' },
    // ['step-measures']: {order: 6, key: 'measures' },
    // ['step-target-weight']: {order: 7, key: 'targetWeight' },
    // ['step-level-of-fitness']: {order: 8, key: 'levelOfFitness' },
    // ['step-love-or-hate']: {order: 9, key: 'loveOrHate' },
    // ['step-workouts']: {order: 10, key: 'workouts' },
    // ['step-workout-issues']: 11,
    // [`step-give-up`]: 12,
    // [`step-additional-goals`]: 13,
    // [`step-attention`]: 14,
    // [`step-push-ups`]: 15,
    // [`step-pull-ups`]: 16,
    // [`step-workout-place`]: 17,
    // [`step-equipment`]: 18,
    // [`step-workout-frequency`]: 19,
    // [`step-workout-duration`]: 20,
    // [`step-levels-of-hormones`]: 21,
    // [`step-water`]: 22,
    // [`step-time`]: 23,
    // [`step-products`]: 24,
    // [`step-challenge`]: 25,
    // [`step-name`]: 26,
    // [`step-date-of-birth`]: 27,
    // [`step-email`] : 28,
    // [`step-commitment`]: 29,
}