export const STEPS_PAGES = {
    goal: 1,
    ['step-target-body']: 2,
    ['step-body-type']: 3,
    ['step-level-of-fat']: 4,
    ['step-problem-areas']: 5,
    ['step-measures']: 6,
    ['step-target-weight']: 7,
    ['step-level-of-fitness']: 8,
    ['step-love-or-hate']: 9,
    ['step-workouts']: 10,
    ['step-workout-issues']: 11,
    [`step-give-up`]: 12,
    [`step-additional-goals`]: 13,
    [`step-attention`]: 14,
    [`step-push-ups`]: 15,
    [`step-pull-ups`]: 16,
    [`step-workout-place`]: 17,
    [`step-equipment`]: 18,
    [`step-workout-frequency`]: 19,
    [`step-workout-duration`]: 20,
    [`step-levels-of-hormones`]: 21,
    [`step-water`]: 22,
    [`step-time`]: 23,
    [`step-products`]: 24,
    [`step-challenge`]: 25,
    [`step-name`]: 26,
    [`step-date-of-birth`]: 27,
    [`step-email`] : 28,
    [`step-commitment`]: 29,
}